# ConTeXt Packaging Scripts
# https://github.com/gucci-on-fleek/context-packaging
# SPDX-License-Identifier: CC0-1.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
when:
  - event:
      - tag

steps:
  - name: Generate the release
    image: maxchernoff.ca/tex:latest
    pull: true
    commands:
      - source ./scripts/make-release.sh

  - name: Release
    when:
        event: tag
    image: docker.io/woodpeckerci/plugin-release
    settings:
        overwrite: false
        title: ./output/version.txt
        note: ./files/release-notes.md
        files:
          - ./output/context.ctan.zip
          - ./output/context.tds.zip
          - ./output/context.bin.zip
          - ./output/context-nonfree.tds.zip
        file-exists: fail
        api_key:
            from_secret: GITHUB_TOKEN

  - name: Email on failure
    image: docker.io/deblan/woodpecker-email:latest
    when:
        status:
          - failure
    settings:
        level: failure
        dsn:
            from_secret: EMAIL_DSN
        from:
            address: "woodpecker@noreply.maxchernoff.ca"
        recipients:
          - "server-status@maxchernoff.ca"
        recipients_only: true
        content:
            subject: >
                [{{ pipeline.status }}]
                {{ repo.full_name }}
                ({{ commit.branch }} - {{ commit.sha[0:8] }})"
            body: |
                {{ commit.sha }}<br>
                {{ pipeline.status }}<br>
                {{ commit.author_email }}<br>
